"""add suggestion_cache and cache_id fk

Revision ID: 788f7af672df
Revises: 0001_initial_schema
Create Date: 2026-05-16 13:18:10.591230
"""

from alembic import op
import sqlalchemy as sa



revision = '788f7af672df'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('suggestion_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_shareable', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_cache_content_hash'), 'suggestion_cache', ['content_hash'], unique=True)
    op.add_column('agent_suggestions', sa.Column('cache_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_suggestions_cache_id'), 'agent_suggestions', ['cache_id'], unique=False)
    op.create_foreign_key(None, 'agent_suggestions', 'suggestion_cache', ['cache_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_suggestions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_suggestions_cache_id'), table_name='agent_suggestions')
    op.drop_column('agent_suggestions', 'cache_id')
    op.drop_index(op.f('ix_suggestion_cache_content_hash'), table_name='suggestion_cache')
    op.drop_table('suggestion_cache')
    # ### end Alembic commands ###
